---
version: 2

sphinx:
    configuration: doc/conf.py

formats: all

python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - docs

build:
    os: "ubuntu-22.04"
    apt_packages:
        - libsodium23
    tools:
        python: "3.11"
