#!/usr/bin/python3.8

from sys import argv
from pvss import SystemParameters, PublicKey, PrivateKey

if len(argv) != 5:
    exit(f"Usage: {argv[0]} <params_file> <name> <priv_file> <pub_file>")

with open(argv[1], "rb") as fp:
    params = SystemParameters.decode(fp.read())

priv = PrivateKey.create(params, priv=params.pre_group.rand)

with open(argv[3], "wb") as fp:
    fp.write(priv.der)

with open(argv[4], "wb") as fp:
    fp.write(priv.pub(argv[2]).der)
